admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

stat:
    resource: "@StatBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"