<?php

namespace StatBundle\Repository;

/**
 * ClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get classes list withouth hidden one and ordered
     *
     * @return array
     */
    public function getAllClassesOrdered()
    {
        $queryBuilder = $this->createQueryBuilder('c');

        $queryBuilder
            ->select('c')
            ->join('c.faction', 'f')
            ->where('c.visible = true')
            ->orderBy('f.name, c.name');

        return $queryBuilder
            ->getQuery()
            ->getResult();
    }
}
