<?php

namespace StatBundle\Repository;

/**
 * UserClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserClasseRepository extends \Doctrine\ORM\EntityRepository
{
}
